version: "3.8"

services:
  stubby-default:
    image: tschaffter/getdns-stubby:1.7.0
    container_name: dns-stubby-default
    restart: always
    networks:
      - dns
      - dns-internal
    volumes:
      - ./stubby/stubby-default.yml:/usr/local/etc/stubby/stubby.yml:ro

  dnsmasq-default:
    image: tschaffter/dnsmasq:2.85
    container_name: dns-dnsmasq-default
    restart: always
    command: ["dnsmasq", "-k", "--server", "stubby-default"]
    networks:
      - dns-internal
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf:ro
      - ./dnsmasq/dnsmasq.d/example.com.conf:/etc/dnsmasq.d/example.com.conf:ro
    depends_on:
      - stubby-default

  # stubby-vlan10:
  #   image: tschaffter/getdns-stubby:1.6.0
  #   container_name: stubby-vlan10
  #   restart: always
  #   networks:
  #     - dns-vlan10
  #   volumes:
  #     - ./stubby/stubby-iot.yml:/usr/local/etc/stubby/stubby.yml:ro

  # dnsmasq-vlan10:
  #   image: tschaffter/dnsmasq:0.3.0
  #   container_name: dnsmasq-vlan10
  #   restart: always
  #   command: ["dnsmasq", "-k", "--server", "stubby-vlan10"]
  #   networks:
  #     - dns-vlan10
  #     - dns
  #   volumes:
  #     - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf:ro
  #     - ./dnsmasq/dnsmasq.d/example.com.conf:/etc/dnsmasq.d/example.com.conf:ro
  #   depends_on:
  #     - stubby-vlan10

  nginx:
    image: nginx:1.21.1-alpine
    container_name: dns-nginx
    restart: always
    environment:
      - DNSMASQ_DEFAULT_HOST=dnsmasq-default
      # - DNSMASQ_VLAN10_HOST=dnsmasq-vlan10
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/templates/events.conf:/etc/nginx/templates/events.conf.template:ro
      - ./nginx/templates/stream.conf:/etc/nginx/templates/stream.conf.template:ro
    networks:
      - dns
      - dns-internal
    ports:
      - "53:53/udp"
    depends_on:
      - dnsmasq-default
      # - dnsmasq-vlan10

networks:
  dns:
  dns-internal:
    # internal: true
